esphome:
  name: reterminal-e1001
  friendly_name: reTerminal E1001

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Declaration du capteur home assistante sensor.nantes_temperature
sensor:
  - platform: homeassistant
    id: temperature_nantes
    entity_id: sensor.nantes_temperature

# define font to display words
font:
  - file: "gfonts://Inter@700"
    id: myFont
    size: 36

# define SPI interface
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO9

# Configuration for the Waveshare e-paper display
display:
  - platform: waveshare_epaper
    id: epaper_display
    model: 7.50inv2                         # Specific model of the display
    cs_pin: GPIO10                          # SPI Chip Select pin
    dc_pin: GPIO11                          # Data/Command control pin
    reset_pin:
      number: GPIO12                        # Reset pin for the display
      inverted: false                       # Reset pin logic not inverted
    busy_pin:
      number: GPIO13                        # Busy pin to check display update status
      inverted: true                        # Busy pin logic inverted
    update_interval: 60s                    # Update the display every 60 seconds

    # Lambda function to draw on the display using provided font
    lambda: |-    
      it.printf(20, 50, id(myFont), "Temperature: %.1f °C", id(temperature_nantes).state);
